# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 138a747957285122b983161a072309cc68387d16a1679964d650f8799d4cf78ca94c9283fe895b41b5011fc566e3f077f7f90caf0ea612bc43216b0d91ec4aab

test:
  secret_key_base: da014d4f6f23fa90519b5245213e33a7cd459620b90f09462ad54bd397ed5346615e85126ccae9685c0a950a44166a1325d5299f569235382e43038ad58d45bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
